### ISSUE TITLE
Single line objects

### ISSUE THREAD

**Issue by Default4152** [MatthieuGuille/code-cademy-projects#3]
Simplify - On line 211 and 172 for example, it is generally more preferred to space out your single line objects.

`{article: savedArticle}`

vs

`{ article: savedArticle }`

Read more here: https://github.com/airbnb/javascript#whitespace--in-braces

This is a minor problem but will help your code be even easier to read.

**Comment by MatthieuGuille** [comment]
Thanks for the feedback. Modified to follow best practices and reuploaded
